[package]
name = "stream-sink"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-core = { version = "0.3.30", default-features = false }
futures-sink = { version = "0.3.30", default-features = false }


pin-project = "1.1.5"
